version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: gradle:5.6-jdk12
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Report Coverage
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_test_results:
          path: build/test-results
